#!/usr/bin/env python3
"""Common PostgreSQL branch contract, independently of latency sampling.

Run AFTER the quiet latency benchmark. Uses the same environment credentials as
compare_services.py. Creates two disposable branches per provider and awaits
deletion; never modifies the source database.
"""
import argparse
import datetime
import json
import os
from pathlib import Path
import time
import uuid

import psycopg

from compare_services import API


def main():
    p = argparse.ArgumentParser(description=__doc__)
    p.add_argument('--root', required=True)
    p.add_argument('--ardent-connector', required=True)
    p.add_argument('--report', type=Path, required=True)
    p.add_argument('--anybranch-api', default='http://127.0.0.1:7432')
    a = p.parse_args()
    report = {'state': 'running', 'started_at': datetime.datetime.now(datetime.timezone.utc).isoformat(),
              'providers': {}, 'unverified': ['source RLS/role/extension fidelity',
              'Ardent reset/suspend/restart (no corresponding public CLI/API command found)',
              'website flow', 'source failover and replication recovery parity']}
    a.report.parent.mkdir(parents=True, exist_ok=True)

    def save():
        tmp = a.report.with_suffix('.tmp')
        tmp.write_text(json.dumps(report, indent=2) + '\n')
        tmp.replace(a.report)

    def connect(url):
        return psycopg.connect(url, autocommit=True, connect_timeout=10)

    for provider in ['anybranch', 'ardent']:
        api = API(a.anybranch_api if provider == 'anybranch' else 'https://api.tryardent.com',
                  os.environ['ANYBRANCH_TOKEN' if provider == 'anybranch' else 'ARDENT_TOKEN'], .1, 180)
        data = report['providers'][provider] = {'checks': [], 'cleanup': [], 'state': 'running'}
        branches = []

        def check(ok, name):
            data['checks'].append({'name': name, 'passed': bool(ok)})
            save()
            if not ok:
                raise AssertionError(name)

        def denied(conn, statement, name):
            try:
                conn.execute(statement)
            except psycopg.errors.InsufficientPrivilege:
                check(True, name)
            else:
                check(False, name)

        try:
            for _ in range(2):
                name = 'contract-' + uuid.uuid4().hex[:16]
                entry = {'name': name}
                # Save the operation handle immediately so interrupted creation is recoverable.
                data.setdefault('operations', []).append(entry)
                if provider == 'anybranch':
                    op = api.request('/v1/commands', ['create', name, '--from', a.root, '--print-url'])
                else:
                    op = api.request('/v1/branch/create', {'connector_id': a.ardent_connector, 'service_type': 'postgres', 'name': name})
                entry['id'] = op.get('operation_id') or op.get('id')
                save()
                result = api.wait(provider, op)
                if provider == 'anybranch':
                    url, branch_id = result['stdout'].strip(), name
                else:
                    branch = result.get('branch') or result
                    url = branch.get('branch_url') or result['branch_url']
                    branch_id = branch.get('id') or result['branch_id']
                branches.append((branch_id, url))
            with connect(branches[0][1]) as db, connect(branches[1][1]) as sibling:
                role = db.execute('SELECT rolsuper, rolcreaterole, rolreplication FROM pg_roles WHERE rolname=current_user').fetchone()
                check(role == (False, False, False), 'agent has no superuser, role-admin or replication privilege')
                db.execute("CREATE TYPE public.contract_state AS ENUM ('new','done')")
                db.execute("CREATE TABLE public.contract_parent (id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, value text UNIQUE NOT NULL, amount numeric CHECK(amount>=0), tags text[], body jsonb, state public.contract_state DEFAULT 'new')")
                db.execute("CREATE TABLE public.contract_child (parent_id bigint REFERENCES public.contract_parent(id) DEFERRABLE INITIALLY DEFERRED)")
                db.execute("CREATE FUNCTION public.contract_upper() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN NEW.value=upper(NEW.value); RETURN NEW; END $$")
                db.execute("CREATE TRIGGER contract_upper BEFORE INSERT OR UPDATE ON public.contract_parent FOR EACH ROW EXECUTE FUNCTION public.contract_upper()")
                db.execute("CREATE VIEW public.contract_view AS SELECT id,value FROM public.contract_parent")
                with db.transaction():
                    identity = db.execute("INSERT INTO public.contract_parent(value,amount,tags,body) VALUES ('hello',1.25,ARRAY['one','two'],'{\"valid\":true}'::jsonb) RETURNING id").fetchone()[0]
                    db.execute('INSERT INTO public.contract_child VALUES (%s)', [identity])
                check(db.execute('SELECT value FROM public.contract_view WHERE id=%s', [identity]).fetchone()[0] == 'HELLO', 'identity, trigger, view and committed insert')
                check(db.execute("SELECT tags,body->>'valid',state::text FROM public.contract_parent WHERE id=%s", [identity]).fetchone() == (['one', 'two'], 'true', 'new'), 'array, JSONB and enum/default fidelity')
                try:
                    with db.transaction():
                        db.execute('UPDATE public.contract_parent SET amount=99 WHERE id=%s', [identity])
                        db.execute('INSERT INTO public.contract_child VALUES (-1)')
                except psycopg.errors.ForeignKeyViolation:
                    pass
                check(str(db.execute('SELECT amount FROM public.contract_parent WHERE id=%s', [identity]).fetchone()[0]) == '1.25', 'deferred foreign key rolls back entire transaction')
                try:
                    db.execute("INSERT INTO public.contract_parent(value,amount) VALUES ('hello',2)")
                except psycopg.errors.UniqueViolation:
                    check(True, 'unique constraint enforced')
                else:
                    check(False, 'unique constraint enforced')
                db.execute('ALTER TABLE public.contract_parent ADD COLUMN extra text DEFAULT \'present\'')
                db.execute('CREATE INDEX contract_amount ON public.contract_parent(amount)')
                check(db.execute('SELECT extra FROM public.contract_parent WHERE id=%s', [identity]).fetchone()[0] == 'present', 'ALTER TABLE default and index creation')
                db.execute('DELETE FROM public.contract_child WHERE parent_id=%s', [identity])
                check(db.execute('SELECT count(*) FROM public.contract_child').fetchone()[0] == 0, 'delete committed')
                check(sibling.execute("SELECT to_regclass('public.contract_parent')").fetchone()[0] is None, 'simultaneously live sibling isolated from DDL and writes')
                denied(db, "SELECT pg_read_file('/etc/passwd',0,1)", 'host file access denied')
                denied(db, "COPY (SELECT 1) TO PROGRAM 'true'", 'host program execution denied')
            with connect(branches[0][1]) as fresh:
                check(fresh.execute('SELECT value FROM public.contract_parent WHERE id=%s', [identity]).fetchone()[0] == 'HELLO', 'new connection sees committed data')
            with connect(os.environ['BENCHMARK_SOURCE_URL']) as source:
                check(source.execute("SELECT to_regclass('public.contract_parent')").fetchone()[0] is None, 'source isolated from branch schema and writes')
            data['state'] = 'passed'
        except Exception as exc:
            data.update(state='failed', error_type=type(exc).__name__)
            if isinstance(exc, AssertionError):
                data['failed_check'] = str(exc)
        finally:
            for branch_id, url in branches:
                cleanup = {'branch_id': branch_id, 'success': False}
                data['cleanup'].append(cleanup)
                held = None
                try:
                    held = connect(url)
                    started = time.perf_counter()
                    if provider == 'anybranch':
                        op = api.request('/v1/commands', ['rm', branch_id])
                    else:
                        op = api.request('/v1/cli/branches/' + branch_id, method='DELETE')
                    cleanup['operation_id'] = op.get('operation_id') or op.get('id')
                    save()
                    api.wait(provider, op)
                    cleanup['operation_complete_ms'] = (time.perf_counter() - started) * 1000
                    try:
                        held.execute('SELECT 1')
                    except psycopg.OperationalError:
                        pass
                    else:
                        raise AssertionError('deleted branch still serves existing connection')
                    try:
                        with connect(url):
                            pass
                    except psycopg.OperationalError:
                        pass
                    else:
                        raise AssertionError('deleted branch still accepts new connection')
                    cleanup['success'] = True
                except Exception as exc:
                    cleanup['error_type'] = type(exc).__name__
                    if isinstance(exc, AssertionError):
                        cleanup['failed_check'] = str(exc)
                finally:
                    if held:
                        held.close()
                    save()
    report['state'] = 'passed' if all(d['state'] == 'passed' and all(c['success'] for c in d['cleanup']) for d in report['providers'].values()) else 'failed'
    report['completed_at'] = datetime.datetime.now(datetime.timezone.utc).isoformat()
    save()
    return 0 if report['state'] == 'passed' else 1


if __name__ == '__main__':
    raise SystemExit(main())
